//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.20 at 03:27:09 下午 TST 
//


package com.fpg.ec.codegen.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DbConnection"/>
 *         &lt;element ref="{}Object"/>
 *         &lt;element ref="{}Tables"/>
 *         &lt;element ref="{}page"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dbConnection",
    "object",
    "tables",
    "page"
})
@XmlRootElement(name = "codeGenConfig")
public class CodeGenConfig {

    @XmlElement(name = "DbConnection", required = true)
    protected DbConnection dbConnection;
    @XmlElement(name = "Object", required = true)
    protected Object object;
    @XmlElement(name = "Tables", required = true)
    protected Tables tables;
    @XmlElement(required = true)
    protected Page page;

    /**
     * Gets the value of the dbConnection property.
     * 
     * @return
     *     possible object is
     *     {@link DbConnection }
     *     
     */
    public DbConnection getDbConnection() {
        return dbConnection;
    }

    /**
     * Sets the value of the dbConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link DbConnection }
     *     
     */
    public void setDbConnection(DbConnection value) {
        this.dbConnection = value;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setObject(Object value) {
        this.object = value;
    }

    /**
     * Gets the value of the tables property.
     * 
     * @return
     *     possible object is
     *     {@link Tables }
     *     
     */
    public Tables getTables() {
        return tables;
    }

    /**
     * Sets the value of the tables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tables }
     *     
     */
    public void setTables(Tables value) {
        this.tables = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link Page }
     *     
     */
    public Page getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link Page }
     *     
     */
    public void setPage(Page value) {
        this.page = value;
    }

}
